#!/bin/bash

export LC_ALL=C

pushd scripts
ghc -o toposort -O2 toposort.hs -package archlinux
popd

(cd habs-new && ../scripts/toposort) | while read name
do
  sudo scripts/build-package habs-new/$name i686
  sudo scripts/build-package habs-new/$name x86_64
done

