#!/bin/bash

for i in "$@"
do
  ( source $i/PKGBUILD
    if [ -z "${_hkgname}" ]; then
      basename $source | sed -r -e "s/(.*)-(.*).tar.(gz|bz2)/$pkgname \1 \2 $pkgrel/"
    else
      echo "${pkgname} ${_hkgname} ${pkgver} ${pkgrel}"
    fi
  ) || exit 1
done

