#!/bin/bash
# This scripts lists any packages which are neither in the repository
# neither in pacman's database

# Make Ctrl-C usable
trap "exit 1" 2

for p in *
do
  source $p/PKGBUILD
  for i in ${depends[@]} ${makedepends[@]}
  do
    i=${i%>*}
    i=${i%=*}
    i=${i%<*}
    if [ -d "$i" ] || [ "$i" == "gmp" ] || [ "$i" == "ghc" ]; then
        true
    else
        pacman -Si "$i" > /dev/null
    fi
  done
done

