#!/bin/bash

set -eu

export LC_ALL=C

scripts/toposort habs | while read name
do
    source habs/$name/PKGBUILD
    pkgspec=$pkgname-$pkgver-$pkgrel
    if [ -f "/var/tmp/chroot-i686/copy/repo/$pkgspec-i686.pkg.tar.xz" ]
    then
        echo "Not building $name (already built)."
        continue
    else
        echo "Begin building $name..."
        scripts/build-package habs/$name i686
        #scripts/build-package habs/$name x86_64
    fi
done

