#!/bin/bash
# Run me with sudo !

set -e

export LC_ALL=C

if ! [ -f "scripts/toposort" ]; then
  pushd scripts
  ghc -o toposort -O2 toposort.hs -package archlinux
  popd
fi

[[ x"$1" == x"force" ]] && force=1 || force=0

(cd habs && ../scripts/toposort) | while read name
do
    source habs/$name/PKGBUILD
    pkgspec=$pkgname-$pkgver-$pkgrel
    if [ -f "chroot-i686/copy/repo/$pkgspec-i686.pkg.tar.xz" ]
    then
        echo "Not building $name (already built)."
        continue
    else
        echo "Begin building $name..."
        scripts/build-package habs/$name i686
        #scripts/build-package habs/$name x86_64
    fi
done

