#! /bin/bash

shopt -s nullglob
set -eu

while read archname cabalname pkgver pkgrel; do
  case "${archname},${cabalname},${pkgver},${pkgrel}" in
    ",,,"|"#"*)
      continue			# ignore empty line or comment
      ;;
  esac

  name=$(echo "${cabalname}" | tr 'A-Z-' 'a-z_')

  echo "#"
  echo "PACKAGES += ${name}"
  echo "${name}_cabalname := ${cabalname}"
  echo "${name}_archname := ${archname}"
  echo "${name}_pkgver := ${pkgver}"
  echo "${name}_pkgrel := ${pkgrel}"
done
