#! /bin/bash

shopt -s nullglob
set -eu

pkglist="${1:-PKGLIST}"
habs="${2:-habs}"

exec <"$pkglist"

while read pkgname pkgver pkgrel; do
  pkgbuild=$(egrep -l "^_hkgname=${pkgname}\$" ${habs}/*/PKGBUILD)
  echo "$pkgname-$pkgver -> release $pkgrel -> $pkgbuild"
  sed -r -i -e "s|^pkgrel=[0-9]+$|pkgrel=$pkgrel|" "$pkgbuild"
done
