#!/bin/bash

makechroot() {
  _arch=$1
  _chrootdir="/var/tmp/chroot-${_arch}"
  sudo rm -rf ${_chrootdir}
  sudo mkdir -p ${_chrootdir}
  setarch ${_arch} sudo mkarchroot -f \
    -M /usr/share/devtools/makepkg-${_arch}.conf \
    -C scripts/pacman-haskell.conf \
    ${_chrootdir}/root base base-devel sudo ghc
}

makechroot i686
#makechroot x86_64
